package org.example.data;

import org.example.domain.AccessLevel;
import org.example.domain.Publication;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class PublicationRepository
{
  private static final String QUERY_CREATE      = "CREATE TABLE publication ("
      + "   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL "
      + "   , access_level VARCHAR(10) NOT NULL "
      + "   , title VARCHAR(100) NOT NULL "
      + "   , PRIMARY KEY (id)"
      + ")";
  private static final String QUERY_INSERT      = "INSERT INTO publication (access_level, title) VALUES (?, ?)";
  private static final String QUERY_SELECT      = "SELECT * FROM publication WHERE access_level = COALESCE(?, access_level) AND UPPER(TRIM(BOTH ' ' FROM title)) = UPPER(TRIM(BOTH ' ' FROM COALESCE(?, '')))";
  private static final String QUERY_SELECT_LIKE = "SELECT * FROM publication WHERE access_level = COALESCE(?, access_level) AND UPPER(TRIM(BOTH ' ' FROM title)) LIKE CONCAT('%', UPPER(TRIM(BOTH ' ' FROM COALESCE(?, ''))), '%')";
  private static final String QUERY_UPDATE      = "UPDATE publication SET access_level = ? AND title ? WHERE id = ?";

  private static Connection CONNECTION;

  public List<Publication> findAllByAccessLevelAndTitle(final AccessLevel accessLevel, final String title)
  {
    final List<Publication> records = new ArrayList<>();

    try (final PreparedStatement statement = getConnection().prepareStatement(QUERY_SELECT))
    {
      statement.setObject(1, accessLevel);
      statement.setString(2, title);

      final ResultSet result = statement.executeQuery();

      while (result.next())
      {
        final Publication publication = new Publication();
        publication.setAccessLevel(AccessLevel.valueOf(result.getString("access_level")));
        publication.setID(result.getLong("id"));
        publication.setTitle(result.getString("title"));

        records.add(publication);
      }
    }
    catch (final Throwable t)
    {
      throw new RuntimeException(t);
    }

    return records;
  }

  public List<Publication> findAllByAccessLevelAndTitleLike(final AccessLevel accessLevel, final String title)
  {
    final List<Publication> records = new ArrayList<>();

    try (final PreparedStatement statement = getConnection().prepareStatement(QUERY_SELECT_LIKE))
    {
      statement.setObject(1, accessLevel);
      statement.setString(2, title);

      final ResultSet result = statement.executeQuery();

      while (result.next())
      {
        final Publication publication = new Publication();
        publication.setAccessLevel(AccessLevel.valueOf(result.getString("access_level")));
        publication.setID(result.getLong("id"));
        publication.setTitle(result.getString("title"));

        records.add(publication);
      }
    }
    catch (final Throwable t)
    {
      throw new RuntimeException(t);
    }

    return records;
  }

  public Publication save(final Publication publication)
  {
    if (publication != null)
    {
      final Connection connection = getConnection();

      if (publication.getID() == null)
      {
        try (final PreparedStatement statement = connection.prepareStatement(QUERY_INSERT))
        {
          // Fire an INSERT query.
          statement.setString(1, publication.getAccessLevel().name());
          statement.setString(2, publication.getTitle());

          statement.execute();
        }
        catch (final Throwable t)
        {
          t.printStackTrace();
        }
      }
      else
      {
        try (final PreparedStatement statement = connection.prepareStatement(QUERY_UPDATE))
        {
          // Fire an UPDATE query.
          statement.setString(1, publication.getAccessLevel().name());
          statement.setString(2, publication.getTitle());
          statement.setLong(3, publication.getID());

          statement.execute();
        }
        catch (final Throwable t)
        {
          t.printStackTrace();
        }
      }
    }

    return publication;
  }

  private Connection getConnection()
  {
    if (CONNECTION == null)
    {
      try
      {
        // Register JDBC driver.
        Class.forName("org.h2.Driver");

        // Open a connection.
        CONNECTION = DriverManager.getConnection("jdbc:h2:mem:bug-report");

        // Create the table.
        try (final Statement statement = CONNECTION.createStatement())
        {
          statement.executeUpdate(QUERY_CREATE);
        }
      }
      catch (final Throwable t)
      {
        t.printStackTrace();
      }
    }

    return CONNECTION;
  }
}
